name: Python Lint and Security generator

on:
  push:
    branches: [ "generator" ]

jobs:
  check_with_black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents pushing directly to protected branches

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "."
          src: './src/'

      - name: Commit and Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Apply Black formatting"
          branch: "black-auto-format"
          delete-branch: true
          title: "Auto-format code with Black"
          body: "This PR contains automatic formatting fixes applied by Black."
          labels: "auto-format, black"
          assignees: ${{ github.actor }}

  lint_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r src/requirements.txt
          uv pip install ruff bandit

      - name: Run AI_LIB Ruff
        run: |
          cd src/
          uv run ruff check ./ai_lib
          uv run ruff format --check ./ai_lib

      - name: Run SERVER Ruff
        run: |
          cd src/
          uv run ruff check ./server
          uv run ruff format --check ./server

      - name: Run AI_LIB bandit
        run: |
          cd src/          
          uv run bandit -c bandit.yaml -r ./ai_lib


      - name: Run SERVER bandit
        run: |
          cd src/          
          uv run bandit -c bandit.yaml -r ./server
