name: Python Lint and Security generator

on:
  push:
    branches: [ "*" ]

jobs:

  lint_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv sync
          uv add ruff bandit


      - name: Run SERVER Ruff
        run: |
          cd src/
          uv run ruff check ./server
          uv run ruff format --check ./server


      - name: Run SERVER bandit
        run: |
          cd src/          
          uv run bandit -c bandit.yaml -r ./server
